# Be careful changing these strings because webpay depends on them.
BUYER_UUID_ALREADY_EXISTS = 'BUYER_UUID_ALREADY_EXISTS'
FIELD_REQUIRED = 'FIELD_REQUIRED'
PIN_4_NUMBERS_LONG = 'PIN_4_NUMBERS_LONG'
PIN_ONLY_NUMBERS = 'PIN_ONLY_NUMBERS'
