STATUS_PENDING = 0
STATUS_COMPLETED = 1

STATUS_DEFAULT = STATUS_PENDING

STATUSES = {
    'pending': STATUS_PENDING,
    'completed': STATUS_COMPLETED
}

TYPE_PAYMENT = 0
TYPE_REFUND = 1
TYPE_REJECTED = 2

TYPE_DEFAULT = TYPE_PAYMENT

TYPES = {
    'payment': TYPE_PAYMENT,
    'refund': TYPE_REFUND,
    'rejected': TYPE_REJECTED
}

