from solitude.base import invert

# Please see docs for an explanation of these.
STATUS_PENDING = 0
STATUS_COMPLETED = 1
STATUS_CHECKED = 2
STATUS_RECEIVED = 3
STATUS_FAILED = 4
STATUS_CANCELLED = 5
# These are statuses that reflect the transactions state in solitude
# as it is configured by the client.
STATUS_STARTED = 6
STATUS_ERRORED = 7

STATUS_DEFAULT = STATUS_STARTED

STATUSES = {
    'cancelled': STATUS_CANCELLED,
    'checked': STATUS_CHECKED,
    'completed': STATUS_COMPLETED,
    'failed': STATUS_FAILED,
    'pending': STATUS_PENDING,
    'received': STATUS_RECEIVED,
    'started': STATUS_STARTED,
    'errored': STATUS_ERRORED
}
STATUSES_INVERTED = dict((v, k) for k, v in STATUSES.items())

TYPE_PAYMENT = 0
TYPE_REFUND = 1
TYPE_REVERSAL = 2
TYPE_REFUND_MANUAL = 3
TYPE_REVERSAL_MANUAL = 4

TYPE_DEFAULT = TYPE_PAYMENT

TYPES = {
    'payment': TYPE_PAYMENT,
    'refund': TYPE_REFUND,
    'refund_manual': TYPE_REFUND_MANUAL,
    'reversal': TYPE_REVERSAL,
    'reversal_manual': TYPE_REVERSAL_MANUAL,
}

TYPE_REFUNDS = (TYPE_REFUND, TYPE_REFUND_MANUAL)
TYPE_REVERSALS = (TYPE_REVERSAL, TYPE_REVERSAL_MANUAL)
TYPE_REFUNDS_REVERSALS = TYPE_REFUNDS + TYPE_REVERSALS

PROVIDER_BANGO = 1
PROVIDER_REFERENCE = 2
PROVIDER_BOKU = 3
PROVIDER_BRAINTREE = 4

PROVIDERS = {
    'bango': PROVIDER_BANGO,
    'reference': PROVIDER_REFERENCE,
    'boku': PROVIDER_BOKU,
    'braintree': PROVIDER_BRAINTREE
}

LOG_STATS = 0
LOG_REVENUE = 1

LOGS = {
    'stats': LOG_STATS,
    'revenue': LOG_REVENUE
}

STATUSES_CHOICES = invert(STATUSES)
TYPES_CHOICES = invert(TYPES)
LOG_CHOICES = invert(LOGS)
PROVIDERS_CHOICES = invert(PROVIDERS)
