ACCESS_DENIED = 'ACCESS_DENIED'
INTERNAL_ERROR = 'INTERNAL_ERROR'
INVALID_PACKAGEID = 'INVALID_PACKAGEID'
INVALID_PACKAGE_STATUS = 'INVALID_PACKAGE_STATUS'
INVALID_EMAIL = 'INVALID_EMAIL'
INVALID_PERSON = 'INVALID_PERSON'
INVALID_STRING_LENGTH = 'INVALID_STRING_LENGTH'
INVALID_PARAMETER = 'INVALID_PARAMETER'
OK = 'OK'
SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'


HEADERS_SERVICE = 'x-solitude-service'
HEADERS_SERVICE_GET = 'HTTP_X_SOLITUDE_SERVICE'
