sample_refund = {
    'action_type': 'PAY',
    'charset': 'windows-1252',
    'cancel_url': 'http://some.url/cancel',
    'notify_version': 'UNVERSIONED',
    'pay_key': '1234',
    'payment_request_date': 'Mon Nov 21 15:23:02 PST 2011',
    'reason_code': 'Refund',
    'return_url': 'http://some.url/complete',
    'reverse_all_parallel_payments_on_error': 'false',
    'sender_email': 'some.other@gmail.com',
    'status': 'COMPLETED',
    'tracking_id': '5678',
    'transaction[0].amount': 'USD 1.00',
    'transaction[0].id': 'ABC',
    'transaction[0].id_for_sender_txn': 'DEF',
    'transaction[0].is_primary_receiver': 'false',
    'transaction[0].paymentType': 'DIGITALGOODS',
    'transaction[0].pending_reason': 'NONE',
    'transaction[0].receiver': 'some@gmail.com',
    'transaction[0].refund_account_charged': 'some@gmail.com',
    'transaction[0].refund_amount': 'USD 0.01',
    'transaction[0].refund_id': 'XYZ',
    'transaction[0].status': 'Refunded',
    'transaction[0].status_for_sender_txn': 'Refunded',
    'transaction_type': 'Adjustment',
    'verify_sign': 'xyz'
}

sample_chained_refund = {
    'action_type': 'PAY',
    'charset': 'windows-1252',
    'fees_payer': 'SECONDARYONLY',
    'log_default_shipping_address_in_transaction': 'false',
    'memo': 'Purchase of Sinuous-andy-video-test',
    'notify_version': 'UNVERSIONED',
    'pay_key': '1234',
    'payment_request_date': 'Mon Apr 02 12:51:50 PDT 2012',
    'reason_code': 'Refund',
    'reverse_all_parallel_payments_on_error': 'false',
    'sender_email': 'some-1@gmail.com',
    'status': 'COMPLETED',
    'test_ipn': '1',
    'tracking_id': '5678',
    'transaction[0].amount': 'USD 0.99',
    'transaction[0].id': 'ABC',
    'transaction[0].id_for_sender_txn': 'DEF',
    'transaction[0].is_primary_receiver': 'true',
    'transaction[0].paymentType': 'DIGITALGOODS',
    'transaction[0].pending_reason': 'NONE',
    'transaction[0].receiver': 'some-2@gmail.com',
    'transaction[0].status': 'Refunded',
    'transaction[0].status_for_sender_txn': 'Refunded',
    'transaction[1].amount': 'USD 0.30',
    'transaction[1].id': 'ABC',
    'transaction[1].id_for_sender_txn': 'ASD',
    'transaction[1].is_primary_receiver': 'false',
    'transaction[1].paymentType': 'DIGITALGOODS',
    'transaction[1].pending_reason': 'NONE',
    'transaction[1].receiver': 'some-3@gmail.com',
    'transaction[1].refund_account_charged': 'some-3@gmail.com',
    'transaction[1].refund_amount': 'USD 0.30',
    'transaction[1].refund_id': 'XYX',
    'transaction[1].status': 'Refunded',
    'transaction[1].status_for_sender_txn': 'Refunded',
    'transaction_type': 'Adjustment',
    'verify_sign': 'xyz',
}

sample_purchase = {
    'action_type': 'PAY',
    'cancel_url': 'http://some.url/cancel',
    'charset': 'windows-1252',
    'fees_payer': 'EACHRECEIVER',
    'ipn_notification_url': 'http://some.url.ipn',
    'log_default_shipping_address_in_transaction': 'false',
    'memo': 'Purchase of Sinuous',
    'notify_version': 'UNVERSIONED',
    'pay_key': '1234',
    'payment_request_date': 'Mon Nov 21 22:30:48 PST 2011',
    'return_url': 'http://some.url/return',
    'reverse_all_parallel_payments_on_error': 'false',
    'sender_email': 'some.other@gmail.com',
    'status': 'COMPLETED',
    'test_ipn': '1',
    'tracking_id': '5678',
    'transaction[0].amount': 'USD 0.01',
    'transaction[0].id': 'ABC',
    'transaction[0].id_for_sender_txn': 'DEF',
    'transaction[0].is_primary_receiver': 'false',
    'transaction[0].paymentType': 'DIGITALGOODS',
    'transaction[0].pending_reason': 'NONE',
    'transaction[0].receiver': 'some@gmail.com',
    'transaction[0].status': 'Completed',
    'transaction[0].status_for_sender_txn': 'Completed',
    'transaction_type': 'Adaptive Payment PAY',
    'verify_sign': 'zyx'
}

sample_contribution = {
    'action_type': 'PAY',
    'cancel_url': 'http://some.url/cancel',
    'charset': 'windows-1252',
    'fees_payer': 'EACHRECEIVER',
    'ipn_notification_url': 'http://some.url.ipn',
    'log_default_shipping_address_in_transaction': 'false',
    'memo': 'Contribution for cool addon',
    'notify_version': 'UNVERSIONED',
    'pay_key': '1235',
    'payment_request_date': 'Mon Nov 21 23:20:00 PST 2011',
    'return_url': 'http://some.url/return',
    'reverse_all_parallel_payments_on_error': 'false',
    'sender_email': 'some.other@gmail.com',
    'status': 'COMPLETED',
    'test_ipn': '1',
    'tracking_id': '6789',
    'transaction[0].amount': 'USD 1.00',
    'transaction[0].id': 'yy',
    'transaction[0].id_for_sender_txn': 'xx',
    'transaction[0].is_primary_receiver': 'false',
    'transaction[0].paymentType': 'DIGITALGOODS',
    'transaction[0].pending_reason': 'NONE',
    'transaction[0].receiver': 'some.other@gmail.com',
    'transaction[0].status': 'Completed',
    'transaction[0].status_for_sender_txn': 'Completed',
    'transaction_type': 'Adaptive Payment PAY',
    'verify_sign': 'ZZ'
}

sample_reversal = sample_refund.copy()
sample_reversal['transaction[0].status'] = 'reversal'

gp = 'response.personalData'
rp = 'refundInfoList.refundInfo(0).'
mock_data = {
    'get-verified': {'userInfo.accountType': 'BUSINESS'},
    'get-refund': {},
    'get-personal': {
        gp + '(0).personalDataKey': 'http://axschema.org/contact/country/home',
        gp + '(0).personalDataValue': 'US',
        gp + '(1).personalDataValue': 'batman@gmail.com',
        gp + '(1).personalDataKey': 'http://axschema.org/contact/email',
        gp + '(2).personalDataValue': 'man'
    },
    'get-personal-advanced': {
        gp + '(0).personalDataKey': 'http://schema.openid.net/contact/street1',
        gp + '(0).personalDataValue': '1 Main St',
        gp + '(1).personalDataKey': 'http://schema.openid.net/contact/street2',
        gp + '(2).personalDataValue': 'San Jose',
        gp + '(2).personalDataKey': 'http://axschema.org/contact/city/home'
    },
    'get-permission': {'status': True},
    'get-permission-token': {'token': '%(UUID)s',
                             'tokenSecret': 'secret:%(UUID)s'},
    'check-purchase': {'status': 'COMPLETED', 'pay_key': 'pay-key:%(UUID)s'},
    'get-pay-key': {
        'status': 'COMPLETED', 'pay_key': 'pay-key:%(UUID)s',
        'correlation_id': 'correlation-id:%(UUID)s'},
    'get-preapproval-key': {'preapprovalKey': 'key:%(UUID)s'},
    'request-permission': {'token': 'http://mock.solitude.client'},
    'get-refund': {'responses': {
        rp + 'receiver.amount': '123.45',
        rp + 'receiver.email': 'bob@example.com',
        rp + 'refundFeeAmount': '1.03',
        rp + 'refundGrossAmount': '123.45',
        rp + 'refundNetAmount': '122.42',
        rp + 'refundStatus': 'REFUNDED'}
    },
}
